version: '2'

services:
  test:
    image: graze/php-alpine:7.1-test
    volumes:
      - .:/srv:cached
    working_dir: /srv

  node:
    image: node:8-alpine
    expose:
      - 80
    volumes:
      - ./test/server:/srv:delegated
      - ~/.npm:/root/.npm:delegated
    working_dir: /srv
    command: node -- index.js

  composer:
    image: composer
    volumes:
      - .:/app:delegated
      - ~/.composer:/tmp:delegated
